### ISSUE TITLE
Create Zesty and Artful releases

### ISSUE THREAD

**Issue by skorokithakis** [tmate-io/tmate-ppa#6]
The PPA currently doesn't have a Zesty release, or one for 17.10.

**Comment by javier-lopez** [comment]
Hello @skorokithakis , Zesty and Artful targets have been added to the tmate PPA recipe, please allow up until 24 hrs to see the changes. Let me know if you fine any issues with them.

**Comment by skorokithakis** [comment]
That's great, thank you!

**Comment by nviennot** [comment]
Thank you Javier 😃

**Comment by javier-lopez** [comment]
It seems the packages are already available =), https://launchpad.net/~tmate.io/+archive/ubuntu/archive

**Comment by skorokithakis** [comment]
I can confirm it works great, thanks!
